### ISSUE TITLE
Doesn't work with bech32 addresses

### ISSUE THREAD

**Issue by RubenWaterman** [blockchainofthings/btc-message-verifier#1]
Hey @claudiosdc 

Thanks for adapting the original bitcoinjs-message library! In the example you use, the address bcrt1qwfwu4tawzwdh233qlqwknk2r3quefyalvpwqyg is not actually a valid bitcoin address (they're supposed to start with bc1).

So if I try the package with an actual bitcoin address, i.e. 
```
{
"address":"bc1qklpmx03a8qkv263gy8te36w0z9yafxplc5kwzc",
"signature":"ICFs6oPeLcf5mLguPk+fw2EImalFsamDfpotBnLz1eB1YhZN5DkvPrL315Q0ylwZaQP2XLVWTCHg1c7F7/10WsE=",
"message":"hello"
}
```
I will get an error: `Error: Error verifying message: Non-base58 character`. Any idea on how I could fix this?

**Comment by claudiosdc** [comment]
Hello @RubenWaterman,

Thank you for using Bitcoin Message Verifier.

Now, addressing your questions...

The bech32 address that is used in the examples on the Readme file (bcrt1qwfwu4tawzwdh233qlqwknk2r3quefyalvpwqyg) is not invalid. It is true that all bech32 addresses for the *main* bitcoin network start with 'bc1' as you pointed out. However, the address of the examples is for a *regtest* bitcoin network, a type of bitcoin network that is usually used for development. That is why it starts with 'bcrt1' instead.

As for the error that you are getting, it is due to the fact that the signature that you are trying to verify has not been properly generated for a segwit (bech32) address. Please refer to the Readme file of the [bitcoinjs-message](https://github.com/bitcoinjs/bitcoinjs-message) component, and in particular to the "Sign a Bitcoin message (with segwit addresses)" section.

I am closing this issue since there seems to be nothing wrong with this library.

**Comment by dukaan** [comment]
Hi, I also encountered the problem mentioned by OP.

I signed my message with Electrum and when trying to verify that signature, I get the same base58 error mentioned above.

When I pasted the same data into https://www.verifybitcoinmessage.com/ the signature is actually successfully verified.

Is there something I am missing? Is Electrum messing up the signature somehow? Do you have any idea why it is working inside that web-tool? I think it is also using your library...

Maybe you can help me out. 👍

**Comment by claudiosdc** [comment]
> Hi, I also encountered the problem mentioned by OP.
> 
> I signed my message with Electrum and when trying to verify that signature, I get the same base58 error mentioned above.
> 
> When I pasted the same data into https://www.verifybitcoinmessage.com/ the signature is actually successfully verified.
> 
> Is there something I am missing? Is Electrum messing up the signature somehow? Do you have any idea why it is working inside that web-tool? I think it is also using your library...
> 
> Maybe you can help me out. 👍

@dukaan, this library is NOT expected to work with messages signed with Electrum using segwit addresses. Thus the error that you reported is expected in those cases.

There seems to be a confusion about the usage of this library. It is meant to work for signatures produced ONLY with the bitcoinjs-message library. In particular, whenever a segwit address is used to sign a message, the sigOptions.segwitType property MUST be correctly set (to either 'p2sh(p2wpkh)' or 'p2wpkh'). For more details, please refere to bitcoinjs-message's [Readme file](https://github.com/bitcoinjs/bitcoinjs-message).
