### ISSUE TITLE
A question on formatting

### ISSUE THREAD

**Issue by Iheff** [blockchainofthings/btc-message-verifier#2]
Im using your plugin to verify some signatures - Thanks for your work!

The signatures I am generating can be validated on the web app at verifybitcoinmessage dot com (which seems to use this exact lib), however when I use the lib to verify progrmatically I seem to not be able to catch a valid - I wondered is there any special formatting I should be aware of from between the text input to JS value?

When I copy and paste the same values back to the web app and validate them they seem fine :D

**Comment by claudiosdc** [comment]
@Iheff, how are the signatures that you are trying to validate using this library being generated?

I ask because this library is meant to work for signatures produced ONLY with the bitcoinjs-message library. In particular, whenever a segwit address is used to sign a message, the sigOptions.segwitType property MUST be correctly set (to either 'p2sh(p2wpkh)' or 'p2wpkh'). For more details, please refere to bitcoinjs-message's [Readme file](https://github.com/bitcoinjs/bitcoinjs-message).

**Comment by Iheff** [comment]
I am generating them in a bitbox hardware wallet, they reference legacy addresses of segwits.
What gets me, is copying and pasting my values into the web app (which i think uses this lib) results in a clean validation - so  - maybe this is not the same script but on viewing source of that site it lead me to this package name - maybe you could confirm? (https://www.verifybitcoinmessage.com/  <- this is the site i get a clean validation on when pasting my values in)
And thanks so much for getting back to me - much appreciated :D

**Comment by claudiosdc** [comment]
@Iheff, you are not the first developer who tries to match our library with that web app. They do not seem to be compatible though. Based on a report from another developer, it seems that that web app uses the Electrum's approach to sign messages with segwit addresses (though I cannot confirm it), while our library uses the bitcoinjs-message's approach. I'm sorry.

**Comment by Iheff** [comment]
Thank you so much for confirmation that is super helpful.
great work you have here ... thanks!
